% IMPORTANT: this file should be edited before using this script.
load('D:\Documents\software\MetaLabCore\project_params.mat');

load(fullfile(project_params.raw_dir,'subject_details.mat'));


for s=1:length(subj)
    files = dir(fullfile('D:\Documents\projects\inProgress\detectionVsDiscrimination_fMRI\data\data',...
        ['sub-',subj{s}.scanid],'func','*.tsv'));
    for i =1:length(files)
        tsv2DM0(fullfile('D:\Documents\projects\inProgress\detectionVsDiscrimination_fMRI\data\data',...
        ['sub-',subj{s}.scanid],'func',files(i).name))
        tsv2DM1(fullfile('D:\Documents\projects\inProgress\detectionVsDiscrimination_fMRI\data\data',...
        ['sub-',subj{s}.scanid],'func',files(i).name))
        tsv2DM2(fullfile('D:\Documents\projects\inProgress\detectionVsDiscrimination_fMRI\data\data',...
        ['sub-',subj{s}.scanid],'func',files(i).name))
        DM0_file = dir(fullfile('D:\Documents\projects\inProgress\detectionVsDiscrimination_fMRI\data\data',...
        ['sub-',subj{s}.scanid],'func','*DM0.mat'));
        DM1_file = dir(fullfile('D:\Documents\projects\inProgress\detectionVsDiscrimination_fMRI\data\data',...
        ['sub-',subj{s}.scanid],'func','*DM1.mat'));
        DM2_file = dir(fullfile('D:\Documents\projects\inProgress\detectionVsDiscrimination_fMRI\data\data',...
        ['sub-',subj{s}.scanid],'func','*DM2.mat'));    
        movefile(fullfile('D:\Documents\projects\inProgress\detectionVsDiscrimination_fMRI\data\data',...
        ['sub-',subj{s}.scanid],'func',DM0_file(1).name),...
        fullfile(project_params.data_dir, ['sub-',subj{s}.scanid], 'DM', ...
        ['run-',num2str(i),'_DM0.mat']));  
        movefile(fullfile('D:\Documents\projects\inProgress\detectionVsDiscrimination_fMRI\data\data',...
        ['sub-',subj{s}.scanid],'func',DM1_file(1).name),...
        fullfile(project_params.data_dir, ['sub-',subj{s}.scanid], 'DM', ...
        ['run-',num2str(i),'_DM1.mat']));        
        movefile(fullfile('D:\Documents\projects\inProgress\detectionVsDiscrimination_fMRI\data\data',...
        ['sub-',subj{s}.scanid],'func',DM2_file(1).name),...
        fullfile(project_params.data_dir, ['sub-',subj{s}.scanid], 'DM', ...
        ['run-',num2str(i),'_DM2.mat']));
    end
end